config/routes.rb
HwApp::Application.routes.draw do

  get '/' => "home#index"
  get '/contact' => "home#contact"
  get '/about' => "post#about"
  get '/params_poster/:id' => "post#params_poster"
  get '/links' => "home#links"
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  
  layout "application"

  def index

  	@person = "George Washington"

  end

  def contact

  end

  def about

  end

  def links

  end
  
end

app/controllers/post_controller.rb
class PostController < ActionController::Base

  layout "alternate" 

  def params_poster

  	@id = params[:id]

  @users = [

  	{fname: "Zack", lname: "Feldman",
  	fname: "Joe", lname: "Rivera"
  	}

  ]

  end

  def about

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/contact.html.erb
<h1>CONTACT</h1>

app/views/home/index.html.erb
<h1>INDEX</h1>
<h3><%= @person * 10 %></h3>

<ul>
<li><h1><%= link_to("Links", links_path) %></h1></li>
<li><h1><%= link_to("Contact", contact_path) %></h1></li>
<li><h1><%= link_to("About", about_path) %></h1></li>
</ul>

<h1><b><%= link_to "TEST LINK TO PAGE", links_path %></b></h1>

app/views/home/links.html.erb
<h1>LINKS</h1>
<p><%=  ("joe    ") * 100 %></p>

app/views/layouts/alternate.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HwApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body class="container">
<div class="jumbotron">
<h3>THIS IS THE ALTERNATE LAYOUT</h3>
<%= yield %>
<h3>THIS IS THE ALTERNATE LAYOUT</h3>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HwApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post/_users.html.erb
<% @users.each do|user| %>
	first name: <%= user[:fname] %>

	<br>

<% end %>

app/views/post/about.html.erb
<h1>ABOUT</h1>

app/views/post/params_poster.html.erb
<h3>PARAMS POSTER!</h3>
<h5>The Following Variable Was Passed:
<%= @id %>
</h5>

<%= render 'users', {data: @users} %>